import 'package:shopping_app/models/products_class.dart';

class ProductsList {
  final List<ProductsClass> _products = <ProductsClass>[
    ProductsClass(
      productID: 1,
      productName: 'Smart Phone',
      description:
          'Experience cutting-edge performance with our latest smartphone, featuring a vibrant display, powerful processor, and long-lasting battery life.',
      imagePath: 'assets/shopping/smartphone.jpg',
      price: 499,
      category: 'Electronics/all',
      warranty: '1 year Available',
      deliveryTime: '1-2 Days',
      sellerName: 'Samsung Nepal',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 2,
      productName: 'Face Wash',
      description:
          'Revitalize your skin with our dermatologist-approved face wash, designed to gently cleanse, reduce acne, and promote a radiant complexion.',
      imagePath: 'assets/shopping/facewash.jpg',
      price: 39,
      category: 'Beauty/all',
      warranty: 'No Warranty',
      deliveryTime: '1-2 Days',
      sellerName: 'Lavana',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 3,
      productName: 'GTA V',
      description:
          'Step into the thrilling world of Grand Theft Auto V, an action-packed open-world game full of missions, chaos, and unforgettable characters.',
      imagePath: 'assets/shopping/gtav.jpeg',
      price: 100,
      category: 'Games/all',
      warranty: 'No Warranty',
      deliveryTime: '5-7 Days',
      sellerName: 'Kunyo',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 4,
      productName: 'Keyboard',
      description:
          'Upgrade your typing experience with this hot-swappable mechanical keyboard, featuring tactile switches and customizable RGB lighting.',
      imagePath: 'assets/shopping/keyboard.jpg',
      price: 80,
      category: 'Electronics/all',
      warranty: '1 Year Warranty',
      deliveryTime: '3-5 Days',
      sellerName: 'Backseat Gaming',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 5,
      productName: 'Wireless Earbuds',
      description:
          'Compact and comfortable earbuds with high-fidelity sound and long battery life.',
      imagePath: 'assets/shopping/earbuds.jpg',
      price: 120,
      category: 'Electronics/all',
      warranty: '6 Months Warranty',
      deliveryTime: '2-4 Days',
      sellerName: 'Mi Store',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 6,
      productName: 'Yoga Mat',
      description:
          'Non-slip, eco-friendly yoga mat ideal for both beginners and experts.',
      imagePath: 'assets/shopping/yogamat.jpg',
      price: 25,
      category: 'Clothing/all',
      warranty: 'No Warranty',
      deliveryTime: '1-3 Days',
      sellerName: 'Decathlon',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 7,
      productName: 'Blender',
      description: 'Powerful blender perfect for smoothies, sauces, and soups.',
      imagePath: 'assets/shopping/blender.webp',
      price: 60,
      category: 'Electronics/all',
      warranty: '1 Year Warranty',
      deliveryTime: '2-3 Days',
      sellerName: 'Philips Nepal',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 8,
      productName: 'Bluetooth Speaker',
      description: 'Portable speaker with rich bass and water resistance.',
      imagePath: 'assets/shopping/speaker.jpg',
      price: 75,
      category: 'Electronics/all',
      warranty: '1 Year Warranty',
      deliveryTime: '2-4 Days',
      sellerName: 'JBL Store',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 9,
      productName: 'Denim Jacket',
      description: 'Classic denim jacket that pairs well with any outfit.',
      imagePath: 'assets/shopping/jacket.jpg',
      price: 45,
      category: 'Clothing/all',
      warranty: 'No Warranty',
      deliveryTime: '3-5 Days',
      sellerName: 'H&M Nepal',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 10,
      productName: 'Cookware Set',
      description: 'Durable non-stick cookware set including pans and pots.',
      imagePath: 'assets/shopping/cookware.jpg',
      price: 150,
      category: 'Kitchen/all',
      warranty: '2 Years Warranty',
      deliveryTime: '3-6 Days',
      sellerName: 'Pigeon',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 11,
      productName: 'LED Desk Lamp',
      description:
          'Adjustable LED lamp with touch control and brightness settings.',
      imagePath: 'assets/shopping/desklamp.jpg',
      price: 30,
      category: 'Electronics/all',
      warranty: '1 Year Warranty',
      deliveryTime: '1-3 Days',
      sellerName: 'IKEA Nepal',
      itemQuantity: 0,
    ),
    ProductsClass(
      productID: 12,
      productName: 'Trekking Shoes',
      description: 'Waterproof shoes designed for hiking and rough terrains.',
      imagePath: 'assets/shopping/trekkingshoes.jpg',
      price: 85,
      category: 'Clothing/all',
      warranty: '6 Months Warranty',
      deliveryTime: '2-5 Days',
      sellerName: 'North Face',
      itemQuantity: 0,
    ),
  ];

  List<ProductsClass> get products => _products;
}
